### ISSUE TITLE
404 when installing pipelines with manual approval strategy

### ISSUE THREAD

**Issue by ppitonak** [openshift/tektoncd-pipeline-operator#147]
1. open OpenShift web console
2. navigate to Operators -> Operator Hub -> search for pipelines
3. click install 
4. choose **Manual** approval strategy
5. click on `openshift-pipelines-operator` subscription
6. click on `1 requires approval`

Expected
* I approve the subscription and am able to start using Pipelines

Actual:
* I end up on URL https://console-openshift-console.apps.example.com/k8s/ns/openshift-operators/installplans/install-b2sw2 which only shows `404: Page Not Found`

![tkn_404](https://user-images.githubusercontent.com/445100/70800451-946d6880-1dac-11ea-9cfb-48642c59b448.png)

**Comment by nikhil-thomas** [comment]
@ppitonak  could you check 
`Administration>Custom Resource Dfinitions>InstallPlans>Instances`.
Do you see the install plan `install-b2sw2` listed there.

**Comment by ppitonak** [comment]
@nikhil-thomas I missed your comment.

I tried it again today and still see 404. When I did what you wrote, I see the install plan there. The URL of the plan is 
* https://console-openshift-console.apps.example.com/k8s/ns/openshift-operators/operators.coreos.com~v1alpha1~InstallPlan/install-scz92 

compared to the URL causing 404
* https://console-openshift-console.apps.example.com/k8s/ns/openshift-operators/installplans/install-scz92

**Comment by nikhil-thomas** [comment]
I checked just now on CRC (OpenShift version 4.2.8). It worked fine for me.
Could you try manual channel of someother operator and check whether the issue is there.

If yes could you add a bug in https://github.com/openshift/console

**Comment by ppitonak** [comment]
You are right that it's a bug in console - https://github.com/openshift/console/issues/4224

**Comment by nikhil-thomas** [comment]
@ppitonak Thanks :+1:

**Comment by artrza** [comment]
what is the solution now? I have 404 in openshift pipelines tasks page. cant create any task
