### ISSUE TITLE
Consider adopting Red Hat Upstream First approach with tektoncd-operator

### ISSUE THREAD

**Issue by ron1** [openshift/tektoncd-pipeline-operator#220]
It appears this repo gets much more activity than its upstream github.com/tektoncd/operator repo. In addition, this repo already has a release on OperatorHub.io while its upstream does not. In light of the Red Hat "Upstream First" approach described in this article, https://opensource.com/article/16/12/why-red-hat-takes-upstream-first-approach, consider adopting such an upstream first approach with the tektoncd operator.

**Comment by vdemeester** [comment]
@ron1 thanks for the issue, and you are right on point, we are working towards that goal.
This repository was initiated before [`tektoncd/operator`](https://github.com/tektoncd/operator) while we were making it adopt by upstream. 

It is on our roadmap to sync up both of the repository in the relative shortterm (aka ~2month), but the past few months the focus was put more on the rest of the upstream tekton projects (pipeline, triggers, …) and on driving towards having beta (supported) APIs.

/kind feature

**Comment by ron1** [comment]
@vdemeester thanks for the update. Glad to hear a repo sync is on the near-term roadmap.

How usable is the tektoncd/operator in its current form? Would you recommend folks use this operator until the sync occurs? Also, would you expect this operator to work on OCP 3.11 or is it dependent upon OCP 4.x features.

**Comment by vdemeester** [comment]
@ron1 the next release of tekton (0.11 and beta, …) will require 1.15, so in terms of OpenShift, 4.3 will be the minimum supported version.

**Comment by ron1** [comment]
@vdemeester Any plans to support tekton 0.10 running on older ocp/k8s versions for some period of time?
