### ISSUE TITLE
Unable to configure controller and webhook deployments to pull images from private registry

### ISSUE THREAD

**Issue by ron1** [openshift/tektoncd-pipeline-operator#238]
The pipeline and triggers controller and webhook Deployments created by the openshift-pipelines-operator include image references specific to quay.io. This is a problematic for users that must host these images in a private registry or for disconnected users. Provide a mechanism to make these image references configurable.

**Comment by vdemeester** [comment]
/kind feature
This is more or less in the roadmap (to support air-gapped installation for example) :angel:
