### ISSUE TITLE
tekton-pipelines-controller Deployment references non-existent nop image

### ISSUE THREAD

**Issue by ron1** [openshift/tektoncd-pipeline-operator#241]
The tekton-pipelines-controller Deployment generated by the operator specifies invalid nop-image quay.io/openshift-pipeline/tektoncd-pipeline-nop:v0.10.1. The only relevant tag in quay.io is v0.8.0 not v0.10.1. Is it possible this image is no longer used?

Any problem using tianon/true for the nop-image as is done upstream until this issue is resolved?

**Comment by ron1** [comment]
Any problems using `tianon/true` for the nop-image until this issue is resolved?

**Comment by chmouel** [comment]
@ron1 please use `tianon/true` there is some issue with our build system which we are fixing right now, thanks!
