### ISSUE TITLE
Hit the issue: Namespace does not support install modes for this Operator.

### ISSUE THREAD

**Issue by vincent-pli** [openshift/tektoncd-pipeline-operator#36]
Could someone give some suggestion, thanks a lot
![image](https://user-images.githubusercontent.com/8669744/59476542-cf392700-8e83-11e9-9688-fc31d2401e0a.png)

**Comment by vdemeester** [comment]
/kind bug
/kind question

cc @nikhil-thomas

**Comment by vincent-pli** [comment]
I retry, the issue is gone, so close it, thanks
