### ISSUE TITLE
Installation failure: 'pipelineVersion' and 'triggersVersion' must not be required fields in the config CRD

### ISSUE THREAD

**Issue by jomeier** [openshift/tektoncd-pipeline-operator#449]
Hi,

today I built the operator from master and applied it to my cluster.

The pipelines controller and webhook pods were created. The triggers controller and webhokk pods were missing.

I saw this errors in the operators log: 

```
{"level":"error","ts":1600624840.809676,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"config-controller","request":"/cluster","error":"Config.operator.tekton.dev \"cluster\" is invalid: [status.conditions.pipelineVersion: Required value, status.conditions.triggersVersion: Required value]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\ttektoncd-pipeline-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\ttektoncd-pipeline-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\ttektoncd-pipeline-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\ttektoncd-pipeline-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\ttektoncd-pipeline-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\ttektoncd-pipeline-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\ttektoncd-pipeline-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

I found the problem that the config CRD here:

https://github.com/openshift/tektoncd-pipeline-operator/blob/8834e48495b36d325fa44ccf03f06a6da227dac8/bundle/manifests/operator_v1alpha1_config_crd.yaml#L56

enforces pipelineVersion and triggersVersion being in the status fields but it is not (always) written for example here:

https://github.com/openshift/tektoncd-pipeline-operator/blob/8834e48495b36d325fa44ccf03f06a6da227dac8/pkg/controller/config/config_controller.go#L324

In my opinion pipelineVersion and triggersVersion should both not be required in the config CRD.

Greetings,

Josef

**Comment by piyush-garg** [comment]
This has already been fixed in commit https://github.com/openshift/tektoncd-pipeline-operator/commit/a14910a73bee2e8c764069bcf21fe43055c0bec2#diff-a902125fb652625cb50dc92acd2f65f8

**Comment by piyush-garg** [comment]
Please use the latest master

**Comment by jomeier** [comment]
@piyush-garg 
It is also contained here:
https://github.com/openshift/tektoncd-pipeline-operator/blob/master/bundle/manifests/operator_v1alpha1_config_crd.yaml

and it seems as if this CRD is used in my setup.

**Comment by jomeier** [comment]
@piyush-garg 
It seems like copy & paste. Do you agree that this 'pipelineVersion' and 'triggersVersion' should not be contained in the config CRD in bundle/manifests/operator_v1alpha1_config_crd.yaml ?
