### ISSUE TITLE
Skip installation of Upstream Community Tasks on Power/Z clusters

### ISSUE THREAD

**Issue by nikhil-thomas** [openshift/tektoncd-pipeline-operator#478]
# Current Behavior

Upstream community tasks are installed on all OpenShift Clusters irrespective of the architecture.

Upstream Community Tasks are maintained by non Red Hat contributors. Hence, it is almost impossible to ensure that the step images in those tasks are supported on all architectures (x86,_64, ppc64le, s390x).

# Expected Behavior

Therefore the operator should check the architecture of the cluster (nodes) and skip installation of upstream community task if the platform is not x86_64

**Comment by nikhil-thomas** [comment]
one way to handle this is to add a `platform` check in the `fetchCommunityResources`. We can skip the community resources if the platform is not `x86_64`.

https://github.com/openshift/tektoncd-pipeline-operator/blob/a59f72478cf7fc0aabad132fa9299b2dd7a99a48/pkg/controller/config/config_controller.go#L104

**Comment by snehlatamohite** [comment]
@bahetiamit - Could you please have a look at it?

**Comment by snehlatamohite** [comment]
@nikhil-thomas - Created PR https://github.com/openshift/tektoncd-pipeline-operator/pull/488 to skip upstream community tasks installation if arch is P OR Z.  Please review and do let me know if any changes are needed.

**Comment by nikhil-thomas** [comment]
@snehlatamohite the `check` in you pr is correct, but it is in the `addons` block: https://github.com/openshift/tektoncd-pipeline-operator/blob/f2f3524f29632d9807fd19cc2feb864aede83ab6/pkg/controller/config/config_controller.go#L126

it should be in the `fetchCommunityResources` block: https://github.com/openshift/tektoncd-pipeline-operator/blob/f2f3524f29632d9807fd19cc2feb864aede83ab6/pkg/controller/config/config_controller.go#L105

could you make a patch.

@savitaashture @vdemeester

**Comment by snehlatamohite** [comment]
@nikhil-thomas - Yes I will so the needful and will raise PR for required changes.

**Comment by snehlatamohite** [comment]
@nikhil-thomas  - I have created PR https://github.com/openshift/tektoncd-pipeline-operator/pull/546 added check in fetchCommunityResources please let me know if I need to remove check from readAddons block?
