### ISSUE TITLE
Is it possible to make url of `image` replaceable 

### ISSUE THREAD

**Issue by vincent-pli** [openshift/tektoncd-pipeline-operator#54]
For now the `yaml`s of `application` if fixed in the `deploy/resource`, and it's image is also fixed, like this:
```
quay.io/openshift-pipeline/tektoncd-pipeline-controller:v0.4.0
```
In some private cluster scenario, it's not work.
So I wonder to know, if we have plan to make it replaceable?

**Comment by nikhil-thomas** [comment]
closing https://github.com/openshift/tektoncd-pipeline-operator/pull/69#issuecomment-537463931
