### ISSUE TITLE
Clear seperation of Tasks within PipelineRun Logs

### ISSUE THREAD

**Issue by Homopatrol** [openshift/tektoncd-pipeline-operator#574]
An issue I have found when deploying Pipelines with multiple Tasks is when these Tasks include install commands it fills up a large portion of the Logs therefore making it extrememly hard to navigate around.

The Tekton dashboard has a great feature that allows for realtime analysis of PipelineRun and TaskRun logs - (https://github.com/tektoncd/dashboard)

To make this more accessable could I request adding a feature similar to this to help seperate the Logs by Task in later updates? - This would greatly help and debug.

**Comment by karthikjeeyar** [comment]
@Homopatrol Are you referring to these steps inside a task is hard to navigate and should have its own tab? or is it something else?

![steps](https://user-images.githubusercontent.com/9964343/105143453-e50fd300-5b21-11eb-9c29-c49393af1cf6.gif)

**Comment by Homopatrol** [comment]
@karthikjeeyar Yes the steps inside the task should have its own tab. This is because the output of one step (for example installing) can take up a large portion of logs which means lots of redundant scrolling through afterwards to find the step you need.
