### ISSUE TITLE
tekton-pipelines controller SCC selection

### ISSUE THREAD

**Issue by mtcolman** [openshift/tektoncd-pipeline-operator#634]
Hi, we have a number of clusters, on all of which we've deployed openshift pipelines on via the operator. We are experiencing different behaviour on the different clusters; whereby pipeline pods are being created on some clusters under anyuid scc and the same pods on other clusters and being created under the restricted scc.

I've done some digging and can see we have:
```
$ oc get po -n openshift-pipelines
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-696f95748f-cng4m   1/1     Running   0          115m
tekton-pipelines-webhook-6ccc8fdc6d-lgxh8      1/1     Running   0          100m
tekton-triggers-controller-7d6cc7bb9-k7bnx     1/1     Running   0          100m
tekton-triggers-webhook-775d45569d-48z6s       1/1     Running   0          115m

$ oc get pod tekton-pipelines-controller-696f95748f-cng4m -n openshift-pipelines -oyaml | grep scc
    openshift.io/scc: restricted

$ oc get po -n openshift-pipelines -oyaml | grep scc
      openshift.io/scc: restricted
      openshift.io/scc: restricted
      openshift.io/scc: restricted
      openshift.io/scc: restricted
```

but also on the other cluster, we have:
```
$ oc get pod tekton-pipelines-controller-7c4b9bf4b-8bc7k -oyaml |grep scc
    openshift.io/scc: anyuid
```

(the pipeline pods' SCC selection matches that of the controller on their cluster.)

I cannot understand why we are seeing some pipeline controllers installed with anyuid and some with restricted, unless the user (human) who initiaties the operator install is having their SCC access factored in? (Given that anyuid = priority 10 and all other SCCs are priority=0 and "By default, the anyuid SCC granted to cluster administrators is given priority in their SCC set. This allows cluster administrators to run pods as any user by without specifying a RunAsUser on the pod’s SecurityContext. The administrator may still specify a RunAsUser if they wish." (https://docs.openshift.com/container-platform/4.7/authentication/managing-security-context-constraints.html).

The openshift pipelines operator isn't asking for any permissions only the anyuid can grant, so it should be capable of being deployed under restricted SCC, which is the ideal scenario.

We are using: `Red Hat OpenShift Pipelines Operator1.2.3 provided by Red Hat` and have clusters at 4.5+ running on IBM Coud ROKS.

cc'ing @sionartingstall

Thanks,

Matt

**Comment by SionArtingstall** [comment]
To add to this, it seems as though the controller is "switching" to anyuid as we notice a previously working pipeline then getting permission errors as shown below, which is where are investigations led us to noticing that anyuid had been applied to the tekton-controller and any subsequent task pods spawned  .

```sh
depcheck-scan
STEP-GIT-SOURCE-GIT-SOURCE-6BMGD
{"level":"info","ts":1626687777.0262935,"caller":"git/git.go:157","msg":"Successfully cloned git@github.ibm.com:RedHatGarage/RH_engine_boilerplate.git @ c6d70f0f44219efa6a4fa8ab7016653acb1a8870 (grafted, HEAD, origin/master) in path /workspace/git-source"}
{"level":"info","ts":1626687777.1218672,"caller":"git/git.go:198","msg":"Successfully initialized and updated submodules in path /workspace/git-source"}
STEP-NPM-INSTALL
2021/07/19 09:42:51 unsuccessful cred copy: ".docker" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.docker/config.json: permission denied
2021/07/19 09:42:51 unsuccessful cred copy: ".ssh" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.ssh/known_hosts: permission denied
``
