### ISSUE TITLE
Operator description should link to latest CLI

### ISSUE THREAD

**Issue by siamaksade** [openshift/tektoncd-pipeline-operator#75]
The operator description should only contain a link to the releases page of Tekton CLI to download the latest. The project link should be removed. 

<img width="676" alt="Screenshot 2019-07-15 at 16 02 03" src="https://user-images.githubusercontent.com/1174934/61221946-edf83b00-a719-11e9-86d2-bba54d67c6ba.png">

**Comment by nikhil-thomas** [comment]
Fixed in
https://github.com/operator-framework/community-operators/pull/579
