### ISSUE TITLE
Automate pipeline metrics configurations from 

### ISSUE THREAD

**Issue by hrishin** [openshift/tektoncd-pipeline-operator#87]
The objective of this task is to automate the following metrics related configuration thus a user can see metrics in Grafana and Prometheus as without dealing with external configuration as they install the OpenShift Pipelines.

Configurations:
* Create Prometheus scrape configuration using ServiceMonitor*
* Add RBAC for Prometheus in to perform Service discovery on pipeline deployments 

Issue: https://jira.coreos.com/browse/SRVKP-298

**Comment by nikhil-thomas** [comment]
@hrishin shall we close this issue

**Comment by hrishin** [comment]
@nikhil-thomas yes we can
