### ISSUE TITLE
Remove pre-requisites from operator descriptor 

### ISSUE THREAD

**Issue by siamaksade** [openshift/tektoncd-pipeline-operator#91]
Since there are not pre-requisites for this operator, `Pre-Requisites` should be removed from the operator description instead of stating `none`:
https://github.com/openshift/tektoncd-pipeline-operator/blob/master/deploy/olm-catalog/openshift-pipelines-operator/0.5.2/openshift-pipelines-operator.v0.5.2.clusterserviceversion.yaml#L99

**Comment by nikhil-thomas** [comment]
patch pushed in
https://github.com/operator-framework/community-operators/pull/756
